application/modules/login/views.py
"""
File path: application/modules/login/views.py
Description: login views for App - Define login views
Copyright (c) 2019. This Application has been developed by OR73.
"""
from flask import Blueprint, current_app, flash, redirect, request, render_template, session, url_for
from flask_login import login_required, login_user, logout_user

from .forms import ValidateLoginForm
from .methods import LoginMethod
from application.modules import init_logger

login_bp = Blueprint('login_bp', __name__)


@login_bp.route('/', methods=['GET', 'POST'])
@login_bp.route('/login/', methods=['GET', 'POST'])
def login():
    languages = {'en': 'English', 'es': 'Español'}
    # Login local user
    print('----------------- login %s' % request.method)
    logger = init_logger(__name__, testing_mode=False)
    state = LoginMethod.generate_state_var()
    print('state: ', state)

    if request.method == 'GET':
        current_app.logger.info('LOGIN - <login - GET>: Login form loaded successfully')
        return render_template('login/login.html',
                               state=state)
    if request.method == 'POST':
        print('POST method running for login_bp - Validating User')
        logger.info('LOGIN - <login - POST>: Login form received successfully')
        # Validate login form
        validate_login_form = ValidateLoginForm(request.form)
        logger.info('LOGIN - <login - POST>: Login form send to validation')
        print('validate_login_form: ', validate_login_form)
        if validate_login_form.validate():
            print('|--> Login form validated')
            logger.info('LOGIN - <login - POST>: Login form has been validated successfully for user: <{}>'
                        .format(validate_login_form.email.data))
            # Catch user & password
            email_or_username = validate_login_form.email.data
            password = validate_login_form.password.data
            remember = validate_login_form.remember.data

            print('email_or_username: ', email_or_username)
            email = LoginMethod.get_user_email_by_email_or_username(email_or_username)
            print('email: ', email)

            if email:
                # Validate that user exists
                user_from_db_by_email = LoginMethod.get_user_by_email(email)
                user = LoginMethod.user_method_validate_user(user_from_db_by_email, password)
                print('******* ****** type(user): ', type(user))
                # Check if user actually exists take the login supplied password, hash it,
                #   and compare it to the hashed password in the database if not login or
                #   not check_password_hash(login.password, password
                if not user:
                    print('Provided user email doesn\'t exist, invalid password or user is not active')
                    flash('Something is wrong!!!\n'
                          '\t- Provided email doesn\'t exist\n'
                          '\t- Invalid password\n'
                          '-\tUser is not active')
                    logger.warning('LOGIN - <login - POST>: Something is wrong!!!:\n'
                                   '\t- Provided email doesn\'t exist'
                                   '\t- Invalid password'
                                   '\t- User is not active')
                    return redirect(url_for('login_bp.login',
                                            state=state))
                print('|--> user: ', user)
                # Add the user to session environment
                login_user(user, remember=remember)
                print('The user has been added to current session environment...')

                # Update session data
                session_data = LoginMethod.user_method_session_data(user, state)
                print('Session data updated... session_data: ', session_data)
                update_session(session_data)
                print('Session data updated... session: ', session)

                # Create login register
                new_login = LoginMethod.create_login(user_id=LoginMethod.user_method_get_user_id(user))
                print('new_login: \n', new_login)

                if not new_login:
                    flash('Something was wrong, and session could not be initiated... try again')
                    return redirect(url_for('login_bp.login'))
                flash('Successful Login')
                print('Successful Login')
                print('session: ', session)
                logger.info('LOGIN - <login>: User {} has logged in successfully '.format(email))
                print('-*-*-*-*-*-*-*-*-*-*-*-*-*- User Login')

                language_class = 'flag-icon-co' if session['language'] == 'es' else 'flag-icon-us'
                return redirect(url_for('case_bp.cases_user_login',
                                        language_class=language_class,
                                        state=state))
        else:
            flash('Some provided data is not valid or wrong')
            logger.warning('LOGIN - <login - POST>: A user has provided wrong data ')
            return redirect(url_for('login_bp.login'))


@login_bp.route('/logout/')
@login_required
def logout():
    # Logout & Close current session
    print('-------------------- logout')
    logger = init_logger(__name__, testing_mode=False)
    try:
        logout_user()
        print('session: ', session)
        print('session[access_token]: ', session['access_token'])
        logger.info('LOGIN - <logout>: User {} has logged out successfully '.format(session['email']))
        # Update logout-time in session collection
        LoginMethod.update_logout_time(session['access_token'])
        del session['access_token']
        del session['authenticated']
        del session['email']
        del session['profile']
        del session['session_id']
        del session['username']
        session.modified = True
        return redirect(url_for('login_bp.login'))
    except Exception as e:
        logger.error('LOGIN - <logout>: User {} could not logged out successfully - ERROR: {}'
                     .format(session['username'], e))


# ------------------------ General Methods
def update_session(session_data: dict) -> None:
    # Store all provided data in the current session
    print('------------------- update_session')
    logger = init_logger(__name__, testing_mode=False)
    session['access_token'] = session_data['access_token']
    session['authenticated'] = session_data['authenticated']
    session['email'] = session_data['email']
    session['profile'] = session_data['profile']
    session['provider'] = session_data['provider']
    session['session_id'] = session_data['session_id']
    session['username'] = session_data['username']
    logger.info('update_session: session has been updated successfully')

application/templates/navbar/heading.html
<div class='orPanelHeading'>
    <header>
        <div class='orHeaderTitle'>
            <span class='orHeaderTitleText'>{{ title }}</span>
            <span class='orAlertMessageSpan'>
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        <div class='alert alert-danger orAlertMessage'>{{ messages[0] }}</div> <!-- /.message_alert -->
                    {% endif %}
                {% endwith %}
            </span>
        </div> <!-- /.header_title -->

        <ul class='orNavBar'>
            <li>
                <a class='btn orButtonBlue' id='createCaseBtn' href='#' role='button'
                   data-toggle='modal' data-target='#dialogCreateNewCase'>
                    <i class='fal fa-plus orButtonIcon'></i>Create New Case
                </a>
            </li>
            <li>
                <a href='#' class='orDropdownMenu'>
                    <i class='fad fa-ellipsis-h'></i>
                </a>
                <ul>
                    <li><a id='caseImport' href='#'
                           data-toggle='modal' data-target='#dialogLoadFileCase'>
                        Case - Import
                    </a></li>
                    <li><a id='caseExport' class='orDisableLink' href='#'>Case - Export</a></li>
                </ul>
            </li>
            <li>
                <!--<a href='#en' class='dropdown_menu' id='language_icon'>-->
                <a href='#' class='orDropdownMenu' id='languageIcon'>
                    <span id='languageIconSpan' class='flag-icon {{ language_class }}'></span>
                </a>
                <ul>
                    <li>
                        <a href='{{ url_for("user_bp.set_language", language="en") }}' class='orDropdownMenuLanguage' id='enIcon'>
                        <!--<a href='#en' id='en_icon'>-->
                            <span class='flag-icon flag-icon-us'></span>English
                        </a>
                    </li>
                    <li>
                        <a href='{{ url_for("user_bp.set_language", language="es") }}' class='orDropdownMenuLanguage' id='esIcon'>
                        <!--<a href='#co' id='es_icon'>-->
                            <span class='flag-icon flag-icon-co'></span>Español
                        </a>
                    </li>
                </ul>
            </li>
        </ul>
    </header>
</div> <!-- /.panel -->

application/templates/navbar/navbar.html
<!-- slid-nav 1 -->
<section id='nav1'>
    <nav id='mainNav'>
        <h2 class='orTitle'>
            {{ _('OWL Menu') }}
            <a href='#'>
                <span class='ui-menu-icon float-right' id='menuBtn'>
                    <i class='fad fa-bars' aria-hidden='true' id='changeMenuIcon'></i>
                </span>
            </a>
        </h2>
        <ul class='orUl' id='mainMenu'>
            <li id='user'>
                <a href='#'>
                    <i class='fad fa-user-tie' aria-hidden='true'></i>
                    {{ _('User') }}
                    <i class='fad fa-chevron-left float-right '></i>
                </a>
            </li>
            <li id='case'>
                <a href='#'>
                    <i class='fad fa-suitcase' aria-hidden='true'></i>
                    {{ _('Case') }}
                    <i class='fad fa-chevron-left float-right '></i>
                </a>
            </li>
            <li id='reports'>
                <a href='#'>
                    <i class='fad fa-file-contract' aria-hidden='true'></i>
                    {{ _('Reports') }}
                    <i class='fad fa-chevron-left float-right '></i>
                </a>
            </li>
            <li id='auditTrail'>
                <a href='#'>
                    <i class='fad fa-gavel' aria-hidden='true'></i>
                    {{ _('Audit Trail') }}
                    <i class='fad fa-chevron-left float-right '></i>
                </a>
            </li>
            <li id='logout'>
                <a href='{{ url_for("login_bp.logout") }}'>
                    <i class='fad fa-sign-out' aria-hidden='true'></i>
                    {{ _('Logout') }}
                </a>
            </li>
        </ul>
    </nav>
</section>
<!-- slid_nav 2 -->
<section class='orNav2' id='nav2'>
    <nav class='orMainNavLevel2' id='userSubNav'>
        <h2 class='orTitle'>
            {{ _('User') }}
            <a href='#'>
                <span class='orHomeIcon float-right' id='menuUser'>
                    <i class='fad fa-user-tie' aria-hidden='true'></i>
                </span>
            </a>
        </h2>
        <ul class='orUl'>
            <li class='orBack'>
                <a href='#' class='btn orBackGradientButton'>
                    <i class='fad fa-angle-double-left orBackLink' aria-hidden='true'></i>{{ _('Back') }}
                </a>
            </li>
            <li>
                <a href='#'>
                    <i class='fad fa-users-cog'></i>{{ _('Management') }}
                </a>
            </li>
            <li>
                <a href='#'>
                    <i class='fad fa-user-cog'></i>{{ _('Settings') }}
                </a>
            </li>
        </ul>
    </nav>
</section>
<!-- slid_nav 3 -->
<section class='orNav3' id='nav3'>
    <nav class='orMainNavLevel2' id='caseSubNav'>
        <h2 class='orTitle'>
            {{ _('Case') }}
            <a href='#'>
                <span class='orHomeIcon float-right' id='menuCase'>
                    <i class='fad fa-suitcase' aria-hidden='true'></i>
                </span>
            </a>
        </h2>
        <ul class='orUl' id='mainMenuCase'>
            <li class='orBack'>
                <a href='#' class='btn orBackGradientButton'>
                    <i class='fad fa-angle-double-left orBackLink' aria-hidden='true'></i>{{ _('Back') }}
                </a>
            </li>
            <li id='entities'>
                <a href='#'>
                    <i class='fad fa-chart-network' aria-hidden='true'></i>
                    {{ _('Entities') }}
                    <i class='fad fa-chevron-left float-right '></i>
                </a>
            </li>
            <li id='collectedData'>
                <a href='#'>
                    <i class='fad fa-database'></i>{{ _('Collected Data') }}
                    <i class='fad fa-chevron-left float-right '></i>
                </a>
            </li>
        </ul>
    </nav>
</section>
<!-- slid_nav 4 -->
<section class='orNav4' id='nav4'>
    <nav class='orMainNavLevel2' id='reportsSubNav'>
        <h2 class='orTitle'>
            {{ _('Reports') }}
            <a href='#'>
                <span class='orHomeIcon float-right' id='menuReports'>
                    <i class='fad fa-file-contract' aria-hidden='true'></i>
                </span>
            </a>
        </h2>
        <ul class='orUl'>
            <li class='orBack'>
                <a href='#' class='btn orBackGradientButton'>
                    <i class='fad fa-angle-double-left orBackLink' aria-hidden='true'></i>{{ _('Back') }}
                </a>
            </li>
            <li>
                <a href='#'>
                    <i class='fad fa-file-user'></i>{{ _('User') }}
                </a>
            </li>
            <li>
                <a href='#'>
                    <i class='fad fa-file-invoice'></i>{{ _('Case') }}
                </a>
            </li>
            <li>
                <a href='#'>
                    <i class='fad fa-file-code'></i>{{ _('System') }}
                </a>
            </li>
        </ul>
    </nav>
</section>
<!-- slid_nav 5 -->
<section class='orNav5' id='nav5'>
    <nav class='orMainNavLevel2' id='auditTrailSubNav'>
        <h2 class='orTitle'>
            {{ _('Audit Trail') }}
            <a href='#'>
                <span class='home_icon float-right' id='menuAuditTrail'>
                    <i class='fad fa-gavel' aria-hidden='true'></i>
                </span>
            </a>
        </h2>
        <ul class='orUl'>
            <li class='orBack'>
                <a href='#' class='btn orBackGradientButton'>
                    <i class='fad fa-angle-double-left orBackLink' aria-hidden='true'></i>{{ _('Back') }}
                </a>
            </li>
            <li>
                <a href='#'>
                    <i class='fad fa-chalkboard-teacher'></i>{{ _('User Events') }}
                </a>
            </li>
            <li>
                <a href='#'>
                    <i class='fad fa-users-class'></i>{{ _('All Users') }}
                </a>
            </li>
        </ul>
    </nav>
</section>
<!-- slid_nav 6 -->
<section class='orNav6' id='nav6'>
    <nav class='orMainNavLevel3' id='caseEntitiesNav'>
        <h2 class='orTitle'>
            {{ _('Entities') }}
            <a href='#'>
                <span class='orHomeIcon float-right' id='menuCaseEntities'>
                    <i class='fad fa-chart-network' aria-hidden='true'></i>
                </span>
            </a>
        </h2>
        <ul class='orUl'>
            <li class='orBackLevel'>
                <a href='#' class='btn orBackGradientButton'>
                    <i class='fad fa-angle-double-left orBackLink' aria-hidden='true'></i>{{ _('Back') }}
                </a>
            </li>
            <li>
                <a href='#'>
                    <i class='fad fa-calendar-alt'></i>{{ _('Events') }}
                </a>
            </li>
            <li>
                <a href='#'>
                    <i class='fad fa-map-marked-alt'></i>{{ _('Locations') }}
                </a>
            </li>
            <li>
                <a href='#'>
                    <i class='fad fa-object-ungroup'></i>{{ _('Objects') }}
                </a>
            </li>
            <li>
                <a href='#'>
                    <i class='fad fa-users'></i>{{ _('Persons') }}
                </a>
            </li>
        </ul>
    </nav>
</section>
<!-- slid_nav 7 -->
<section class='orNav7' id='nav7'>
    <nav class='orMainNavLevel3' id='caseCollectedDataNav'>
        <h2 class='orTitle'>
            {{ _('Collected Data') }}
            <a href='#'>
                <span class='orHomeIcon float-right' id='menuCaseCollectedData'>
                    <i class='fad fa-database' aria-hidden='true'></i>
                </span>
            </a>
        </h2>
        <ul class='orUl'>
            <li class='orBackLevel'>
                <a href='#' class='btn orBackGradientButton'>
                    <i class='fad fa-angle-double-left orBackLink' aria-hidden='true'></i>{{ _('Back') }}
                </a>
            </li>
            <li>
                <a href='#'>
                    <i class='fad fa-photo-video'></i>{{ _('Media') }}
                </a>
            </li>
            <li>
                <a href='#'>
                    <i class='fad fa-images'></i>{{ _('Images') }}
                </a>
            </li>
        </ul>
    </nav>
</section>