application/modules/user/forms.py
"""
File Path: application/modules/login/forms.py
Description: Login forms for App - Define login forms
Copyright (c) 2019. This Application has been developed by OR73.
"""
from wtforms import BooleanField, Form, PasswordField, StringField, validators
from wtforms.validators import DataRequired, Email, InputRequired


class ValidateNewUserForm(Form):
    """ Validate login form fields """
    print('----------------- ValidateNewUserForm')
    name = StringField('Name',
                       validators=[DataRequired(message='Enter a valid First & Last Name'),
                                   InputRequired(message='Enter a valid First & Last Name')])
    username = StringField('Username',
                           validators=[DataRequired(message='Enter a valid username min:3 max:12 length'),
                                       InputRequired(message='Enter a valid username min:3 max:12 length'),
                                       validators.length(min=3, max=12)])
    email = StringField('Email',
                        validators=[DataRequired(message='Enter a valid email or username'),
                                    InputRequired(message='Enter a valid email or username')])
    password = PasswordField('Password',
                             validators=[DataRequired(message='Enter a password min 3 length'),
                                         InputRequired(message='Enter a password min 3 length'),
                                         validators.Length(min=3, max=35)])
    profile = StringField('Profile',
                          validators=[DataRequired(message='Select a Profile'),
                                      InputRequired(message='Select a Profile')])

application/modules/user/__init__.py
from .forms import ValidateNewUserForm
from .methods import UserMethod
from .models import User
from .views import user_bp

application/modules/user/views.py
"""
File path: application/modules/user/views.py
Description: Auth models for App - Define login data model
Copyright (c) 2019. This Application has been developed by OR73.
"""
# DELETE: Delete selected user
# GET: Show current user data
# POST: Create new user
# PUT: Update user data
from flask import Blueprint, flash, redirect, request, render_template, session, url_for
from flask_login import current_user, login_required

from .methods import UserMethod
from application.modules import init_logger

user_bp = Blueprint('user_bp', __name__)


# --------------------------------------- users
@user_bp.route('/user/')
@login_required
def users():
    # User login
    print('----------------- user_bp.route(/user/)')
    logger = init_logger(__name__, testing_mode=False)
    # Select user type: admin, manager or user
    print('|--- current_user: ', current_user)
    print('|--- request: ', request)
    print('|--- session: ', session)

    print('~~~~~~~~~~~~ session: ', session)
    profile = session['profile']
    user_method = []
    try:
        state = session['session_id']  # The same state value
        if profile == 'admin':
            print('---------- admin')
            user_method = UserMethod.get_all_users_name()
        elif profile == 'manager':
            print('---------- manager')
            user_method = UserMethod.get_all_users_name_manager(current_user.username)
        elif profile == 'user':
            print('---------- user')
            return redirect(url_for('case_bp.cases_user',
                                    username=current_user.username))
        else:
            # Required profile does not exist
            print('Required profile does not exist')
            logger.critical('Current User: {}\n'
                            '\t\tUSER - <users>: Required profile does not exist'
                            .format(current_user.username))
        if len(user_method) > 0:
            logger.info('Current User: {}\n'
                        '\t\tUSER - <users>: users loaded successfully - len(user_method): {}'
                        .format(current_user.username, len(user_method)))
        return render_template('user/user_zmenu.html',
                               language_class='flag-icon-co' if session['language'] == 'es' else 'flag-icon-us',
                               profile=profile,
                               state=state,
                               users=user_method)
    except Exception as e:
        print('Exception in /user')
        print('error: ', e)
        logger.error('Current User: {}\n'
                     '\t\tUSER - <users>: Something wrong in users...\n'
                     '\t\tERROR: {}'
                     .format(current_user.username, e))
        return render_template('errors/404.html'), 404


@user_bp.route('/user/create/', methods=['GET', 'POST'])
@login_required
def create():
    # User create
    print('----------------- user_bp.route(/user/create/) - {}'.format(request.method))
    logger = init_logger(__name__, testing_mode=False)
    profile = session['profile']
    try:
        if request.method == 'GET':
            logger.info('Current User: {}\n'
                        '\t\tUSER - <create>: user create form loaded successfully'
                        .format(current_user.username))
            return render_template('user/user_create.html',
                                   profile=profile)
        elif request.method == 'POST':
            email_user_data = UserMethod.get_user_by_email(request.form.get('email'))
            username_user_data = UserMethod.get_user_by_username(request.form.get('username'))

            if not email_user_data:
                logger.info('Current User: {}\n'
                            '\t\tUSER - <create>: user email <{}> does not exist in DB'
                            .format(current_user.username, request.form.get('email')))
                if not username_user_data:
                    logger.info('Current User: {}\n'
                                '\t\tUSER - <create>: user username <{}> does not exist in DB'
                                .format(current_user.username, request.form.get('username')))
                    picture = None
                    if 'picture' in request.files:
                        print('picture in request files...')
                        picture = request.files['picture']
                    else:
                        print('picture is not in request files XXX')

                    email = request.form.get('email')
                    username = request.form.get('username')
                    user_data = {
                        '_id': 1,
                        'name': request.form.get('name'),
                        'username': username.replace(' ', ''),
                        'email': email.replace(' ', ''),
                        'picture': '' if not picture else picture.filename,
                        'language': request.form.get('language'),
                        'password': request.form.get('password'),
                        'profile': request.form.get('profile')
                    }
                    user_created = UserMethod.create_user(user_data, picture)
                    if user_created:
                        flash('User created successfully')
                        logger.info('Current User: {}\n'
                                    '\t\tUSER - <create>: user <{}> created successfully'
                                    .format(current_user.username, user_created['username']))
                        return redirect(url_for('user_bp.users',
                                                profile=profile))
                    else:
                        flash('User could not be created...')
                        logger.warning('Current User: {}\n'
                                       '\t\tUSER - <create>: user <{}> could not be created'
                                       .format(current_user.username, user_created['username']))
                        return redirect(url_for('user_bp.users',
                                                profile=profile))
                else:
                    flash('User username already exist in Database, try a different username')
                    logger.warning('Current User: {}\n'
                                   '\t\tUSER - <create>: user <{}> already exist in Database'
                                   .format(current_user.username, request.form.get('username')))
                    return redirect(url_for('user_bp.create',
                                            profile=profile))
            else:
                flash('User email already exist in Database, try a different email')
                logger.warning('Current User: {}\n'
                               '\t\tUSER - <create>: user email <{}> already exist in Database'
                               .format(current_user.username, request.form.get('email')))
                return redirect(url_for('user_bp.create',
                                        profile=profile))
        return redirect(url_for('user_bp.users',
                                profile=profile))
    except Exception as e:
        print('Exception in /user/create/')
        print('error: ', e)
        logger.error('Current User: {}\n'
                     '\t\tUSER - <create>: something is wrong\n\t\tException: {}'
                     .format(current_user.username, e))
        return render_template('errors/404.html'), 404


@user_bp.route('/user/delete/<username>')
@login_required
def delete(username: str):
    # User delete
    print('----------------- user_bp.route(/user/delete/)')
    print('username: ', username)
    logger = init_logger(__name__, testing_mode=False)
    try:
        profile = session['profile']
        user_delete = UserMethod.delete_user_by_username(username)
        if user_delete:
            flash('The user <{}> has been deleted successfully'.format(username))
            logger.info('Current User: {}\n'
                        '\t\tUSER - <delete>: user <{}> has been deleted successfully'
                        .format(current_user.username, username))
        else:
            flash('The user <{}> could not be deleted'.format(username))
            logger.warning('Current User: {}\n'
                           '\t\tUSER - <create>: user <{}> could not be deleted'
                           .format(current_user.username, username))
        return redirect(url_for('user_bp.users',
                                profile=profile))
    except Exception as e:
        print('Exception in /user/delete/{}'.format(username))
        print('error: ', e)
        logger.error('Current User: {}\n'
                     '\t\tUSER - <create>: something is wrong\n'
                     '\t\tException: {}'
                     .format(current_user.username, e))
        return render_template('errors/404.html'), 404


@user_bp.route('/user/image/<filename>')
@login_required
def get_user_image(filename: str):
    # Return filename image
    print('---------------- get_user_image')
    logger = init_logger(__name__, testing_mode=False)
    try:
        return UserMethod.load_user_picture(filename)
    except Exception as e:
        print('Exception in /user/image/{}'.format(filename))
        print('error: ', e)
        logger.warning('Current User: {}\n'
                       '\t\tUSER - <get_user_image>: User image could not be loaded... something is wrong!!!'
                       .format(current_user.username))
        return render_template('errors/404.html'), 404


@user_bp.route('/user/read/<username>')
@login_required
def read(username: str):
    # User read
    print('----------------- user_bp.route(/user/read/)')
    print('username: ', username)
    profile = session['profile']
    logger = init_logger(__name__, testing_mode=False)
    try:

application/templates/user/user_read.html
<!-- show the login page user_read.html -->
{% extends 'base_login.html' %}
{% block content %}
    <nav aria-label='breadcrumb'>
        <ol class='breadcrumb'>
            <li class='breadcrumb-item'><a href='{{ url_for("user_bp.users") }}'>{{ _('Home') }}</a> </li>
            <li class='breadcrumb-item'><a href='{{ url_for("user_bp.users") }}'>{{ _('Users') }}</a></li>
            <li class='breadcrumb-item active'>{{ _('Read User Data') }}</li>
        </ol>
    </nav>
    <h1>{{ _('Read User Data') }}<small> <strong>-</strong> {{ profile }}</small></h1>
    <div class='text-center mb-4'>
        <img class='mb-4' src='{{ url_for("static", filename="dist/img/OWL_logo/OWL_logo_md.png") }}'
             alt='OWL Logo' width='190' height='75'/>
        <h1 class='h3 mb-3 font-weight-normal'>{{ _('User Data') }}</h1>
    </div> <!-- /.text-center -->
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class='alert alert-danger alert_message'>{{ messages[0] }}</div> <!-- /.message_alert -->
        {% endif %}
    {% endwith %}
    <div class='row h-100 justify-content-center align-items-center'>
        <div class='col w-25 h-100 text-center'>
            <div class='img-thumbnail h-100'>
                {% if filename %}
                    <img class='user_img'
                         src='{{ url_for('user_bp.get_user_image', filename=filename) }}'
                         alt='{{ user.username }} picture'/>
                {% else %}
                    <img class='user_img'
                         src='{{ url_for("static", filename="dist/img/default_user_img.png") }}'
                         alt='{{ user.username }} picture'/>
                {% endif %}
            </div> <!-- /.img-thumbnail -->
        </div> <!-- /.col -->
        <div class='col w-75 h-100'>
            <div class='table-responsive-lg user_data_table'>
                <table class='table'>
                    <tbody>
                        <tr>
                            <th scope='row'>{{ _('Name') }}: </th>
                            <td>{{ user.name }}</td>
                        </tr>
                        <tr>
                            <th scope='row'>{{ _('Username') }}:</th>
                            <td>{{ user.username }}</td>
                        </tr>
                        <tr>
                            <th scope='row'>{{ _('Email') }}:</th>
                            <td>{{ user.email }}</td>
                        </tr>
                        <tr>
                            <th scope='row'>{{ _('Profile') }}</th>
                            <td>{{ user.profile }}</td>
                        </tr>
                        <tr>
                            <th scope='row'>{{ _('Active') }}</th>
                            <td>{{ user.active }}</td>
                        </tr>
                        <tr></tr>
                        {% if profile == 'admin' %}
                            <tr class='text-center tr_button'>
                                <td colspan='2'>
                                    <a class='btn btn-primary'
                                       type='submit'
                                       href='{{ url_for("user_bp.update", username=user.username) }}'>
                                        {{ _('Update') }}
                                    </a>
                                    <a class='btn btn-danger'
                                       type='reset'
                                       href='{{ url_for("user_bp.delete", username=user.username) }}'>
                                        {{ _('Delete') }}
                                    </a>
                                </td>
                            </tr>
                        {% endif %}
                    </tbody>
                </table>
            </div> <!-- /.table-responsive-lg -->
        </div> <!-- /.col -->
    </div> <!-- /.row -->
{% endblock %}

application/templates/user/user_update.html
<!-- user_update.html -->
{% extends 'base_login.html' %}
{% block content %}
    <nav aria-label='breadcrumb'>
        <ol class='breadcrumb'>
            <li class='breadcrumb-item'><a href='{{ url_for("user_bp.users") }}'>{{ _('Home') }}</a> </li>
            {% if profile == 'admin' or profile == 'manager' %}
                <li class='breadcrumb-item'><a href='{{ url_for("user_bp.users") }}'>{{ _('Users') }}</a></li>
            {% elif profile == 'user' %}
                <li class='breadcrumb-item'><a href='{{ url_for("user_bp.settings") }}'>{{ _('User') }}</a></li>
            {% endif %}
            {% if is_owner %}
                <li class='breadcrumb-item active'>{{ _('Settings') }}</li>
            {% else %}
                <li class='breadcrumb-item active'>{{ _('Update') }}</li>
            {% endif %}
        </ol>
    </nav>
    {% if is_owner %}
        <h1>{{ _('User Settings') }}<small> <strong>-</strong> {{ profile }}</small></h1>
    {% else %}
        <h1>{{ _('Edit/Update User Data') }}<small> <strong>-</strong> {{ profile }}</small></h1>
    {% endif %}


    <div class='row w-100 align-items-center align-content-center text-center mx-auto'>
        <div class='text-center align-content-center align-items-center mx-auto'>
            <img class='mb-4 logo_img' src='{{ url_for("static", filename="dist/img/OWL_logo/OWL_logo_md.png") }}'
                 alt='OWL Logo'/>
           {% if is_owner %}
                <h1>{{ _('User Settings') }}</h1>
            {% else %}
                <h1>{{ _('Edit/Update User Data') }}</h1>
            {% endif %}
        </div> <!-- /.text-center -->
    </div> <!-- /.row -->

    <div class='row w-100'>
        {% with messages = get_flashed_messages() %}
            {% if messages %}
            <div class='alert alert-danger alert_message'>{{ messages[0] }}</div> <!-- /.message_alert -->
        {% endif %}
        {% endwith %}
    </div> <!-- /.row -->

    <div class='row h-100 w-100 align-items-center'>
        <form class='form-signin' method='POST' action='{{ url_for("user_bp.update", username=user.username) }}' enctype='multipart/form-data'>
            <div class='row w-100 h-100'>
                <div class='col w-25 h-100 text-center'>
                    <div class='img-thumbnail'>
                        {% if filename %}
                            <img id='user_img' class='user_img'
                                 src='{{ url_for('user_bp.get_user_image', filename=filename) }}'
                                 alt='{{ user.username }} picture'/>
                        {% else %}
                            <img id='user_img' class='user_img'
                                 src='{{ url_for("static", filename="dist/img/default_user_img.png") }}'
                                 alt='{{ user.username }} picture'/>
                        {% endif %}
                    </div> <!-- /.img-thumbnail -->
                    <div class='form-group col'>
                        {% if is_owner %}
                            <input id='inputImage' type='file' class='file' data-preview-file-type='any'
                                   name='picture' accept='.jpg, .jpeg, .png' size='256KB' hidden='hidden'/>
                            <button id='update_img' type='button' class='btn btn-dark'>
                                {{ _('Modify user image') }}
                            </button>
                            <div class='valid-feedback'>
                                Valid Field
                            </div> <!-- /.valid-feedback -->
                            <div class='invalid-feedback'>
                                This field is required
                            </div> <!-- /.invalid-feedback -->
                        {% endif %}
                    </div> <!-- /.form-label-group -->
                </div> <!-- /.text-center -->

                <div class='col w-75 h-100'>
                    <div class='form-label-group'>
                        <input type='text' id='inputName' class='form-control' name='name' placeholder='{{ _('First & Last Name') }}' value='{{ user.name }}' required autofocus/>
                        <label for='inputName'>{{ _('First & Last Name') }}</label>
                    </div> <!-- /.form-label-group -->

                    <div class='form-label-group'>
                        <input type='text' id='inputUserName' class='form-control' name='username' placeholder='{{ _('Username') }}' value='{{ user.username }}' required autofocus/>
                        <label for='inputUserName'>{{ _('Username') }}</label>
                    </div> <!-- /.form-label-group -->

                    <div class='form-label-group'>
                        <input type='email' id='inputEmail' class='form-control' name='email' placeholder='{{ _('email') }}' value='{{ user.email }}' required autofocus/>
                        <label for='inputEmail'>{{ _('Email') }}</label>
                    </div> <!-- /.form-label-group -->

                    {% if is_owner %}
                        <div class='form-label-group'>
                            <input type='password' id='inputPassword' class='form-control'
                                   name='password' placeholder='{{ _('Password') }}'
                                   value='Modify Password' required autofocus/>
                            <label for='inputPassword'>{{ _('Password') }}</label>
                        </div> <!-- /.form-label-group -->
                    {% endif %}

                    {% if not is_owner %}
                        <div class='form-group col-md-4'>
                            <label for='active'>{{ _('Active') }}</label>
                            <select id='active' class='form-control' name='active'>
                                {% if user.active == True %}
                                    <option value='True' selected>{{ _('True') }}</option>
                                    <option value='False'>{{ _('False') }}</option>
                                {% else %}
                                    <option value='True'>{{ _('True') }}</option>
                                    <option value='False' selected>{{ _('False') }}</option>
                                {% endif %}
                            </select>
                        </div> <!-- /.form-label-group -->

                        <div class='form-group col-md-4'>
                            <label for='profile'>{{ _('Profile') }}</label>
                            <select id='profile' class='form-control' name='profile'>
                                {% if user.profile == 'user' %}
                                    <option value='user' selected>{{ _('User') }}</option>
                                    <option value='manager'>{{ _('Manager') }}</option>
                                    <option value='admin'>{{ _('Admin') }}</option>
                                {% elif user.profile == 'manager' %}
                                    <option value='user'>{{ _('User') }}</option>
                                    <option value='manager' selected>{{ _('Manager') }}</option>
                                    <option value='admin'>{{ _('Admin') }}</option>
                                {% else %}
                                    <option value='user'>{{ _('User') }}</option>
                                    <option value='manager'>{{ _('Manager') }}</option>
                                    <option value='admin' selected>{{ _('Admin') }}</option>
                                {% endif %}
                            </select>
                        </div> <!-- /.form-label-group -->
                    {% endif %}
                </div> <!-- /.col -->
            </div> <!-- /.row -->
            <div class='row w-100 align-items-center align-content-center text-center'>
                <div class='col w-100 text-center align-items-center align-content-center'>
                    <button class='btn btn-primary' type='submit'>{{ _('Update') }}</button>
                    <button class='btn btn-danger' type='reset'>{{ _('Cancel') }}</button>
                </div> <!-- /.text-center -->
            </div> <!-- /.row -->
        </form>
    </div> <!-- /.row -->
{% endblock %}

application/templates/user/user_zmenu.html
<!-- user_login.html -->
{% extends 'base_login.html' %}
{% block content %}
    <nav aria-label='breadcrumb'>
        <ol class='breadcrumb'>
            <li class='breadcrumb-item'><a href='{{ url_for("user_bp.users") }}'>{{ _('Home') }}</a></li>
            <li class='breadcrumb-item active'>{{ _('Users') }}</li>
        </ol>
    </nav>
    <h1>{{ _('User Main Menu') }}<small> <strong>-</strong> {{ profile }}</small></h1>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class='alert alert-danger alert_message'>{{ messages[0] }}</div> <!-- /.message_alert -->
        {% endif %}
    {% endwith %}
    {% if profile == 'admin' or profile == 'manager' %}
        <section class='d-flex justify-content-center'>
            <div class='row h-100 w-100 align-content-center'>
                <div class='col col-md-10 w-100 mx-auto text-center align-content-center'>
                    {% if profile == 'admin' %}
                        <a class='btn btn-outline-success main_menu_button create_button' data-placement='top'
                           href='{{ url_for("user_bp.create") }}' data-toggle='tooltip' title='Create User'
                           type='button'>
                            <i class='fas fa-user-plus i_create'></i>
                            <p>{{ _('Create User') }}</p>
                        </a>
                    {% endif %}
                    {% if users %}
                        <table class='table main_menu_table w-100'>
                            <thead>
                                <tr>
                                    <th scope='col'>{{ _('Username') }}</th>
                                    <th scope='col'>{{ _('Profile') }}</th>
                                    <th scope='col'>{{ _('Group User') }}</th>
                                    {% if profile == 'admin' %}<th scope='col'>{{ _('Group Manager') }}</th>{% endif %}
                                    <th></th>
                                    {% if profile == 'admin' %}<th></th><th></th>{% endif %}
                                </tr>
                            </thead>
                            <tbody>
                                {% for user in users %}
                                    <tr class='justify-content-center main_tr'>
                                        <td class='text-left align-middle'>{{ user.username }}</td>
                                        <td class='text-left align-middle'>{{ user.profile }}</td>
                                        <td class='text-left align-middle'>
                                            {% for group in user.user_groups %}
                                                <a href='{{ url_for("group_bp.read", group_name=group) }}' class='link_without_deco'>
                                                    {{ group }}
                                                </a>
                                            {% endfor %}
                                        </td>
                                        {% if profile == 'admin' %}
                                            <td class='text-left align-middle'>
                                                {% for group in user.user_groups_manager %}
                                                    <a href='{{ url_for("group_bp.read", group_name=group) }}', class='link_without_deco'>
                                                        {{ group }}
                                                    </a>
                                                {% endfor %}
                                            </td>
                                        {% endif %}

                                        <td class='text-left align-middle'>
                                            <a class='btn btn-outline-info main_menu_button'
                                               data-toggle='tooltip' data-placement='top'
                                               title={{ _('Read User') }} href='{{ url_for("user_bp.read", username=user.username) }}'>
                                                <i class='fas fa-user i_read'></i>
                                            </a>
                                        </td>
                                        {% if profile == 'admin' %}
                                            <td class='text-left align-middle'>
                                                <a class='btn btn-outline-secondary main_menu_button'
                                                   data-toggle='tooltip' data-placement='top'
                                                   title={{ _('Update User') }} href='{{ url_for("user_bp.update", username=user.username) }}'>
                                                    <i class='fas fa-user-edit i_update'></i>
                                                </a>
                                            </td>
                                            <td class='text-left align-middle'>
                                                <a class='btn btn-outline-danger main_menu_button'
                                                   data-toggle='tooltip' data-placement='top'
                                                   title={{ _('Delete User') }} href='{{ url_for("user_bp.delete", username=user.username) }}'>
                                                    <i class='fas fa-user-minus i_delete'></i>
                                                </a>
                                            </td>
                                        {% endif %}
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <div><h2>{{ _('Database does not contain any User') }}</h2></div>
                    {% endif %}
                </div> <!-- /.col -->
            </div> <!-- /.row -->
        </section>

    {% elif profile == 'user' %}
    {% endif %}
{% endblock %}