application/modules/case/models.py
"""
File Path: application/modules/case/models.py
Description: Case models for App - Define Case models
Copyright (c) 2019. This Application has been developed by OR73.
"""
from datetime import datetime


class Case:
    def __init__(self, case):
        self.__id = case['id']
        self.__name = case['name']
        self.__description = case['description']
        self.__caseStatus = case['status']
        self.__caseType = case['type']
        self.__groups = case['groups'] if 'groups' in case else []
        
        self.__clientId = case['clientId']
        self.__clientName = case['clientName']
        
        self.__creationDate = self.set_current_date()
        self.__dueDate = self.string_to_datetime(case['dueDate'])
        self.__lastModificationDate = self.set_current_date()

    def __repr__(self) -> str:
        return ('<\n'
                '\t-------   CASE DATA -------\n'
                '\tCase ID: {}\n'
                '\tCase name: {}\n'
                '\tDescription: {}\n'
                '\tCase Status: {}\n'
                '\tCase Type: {}\n'
                '\t-------   CASE ADDITIONAL DATA -------\n'
                '\tCase Groups: {}\n'
                '\tClient ID: {}\n'
                '\tClient name: {}\n'
                '\t-------   CASE DATES -------\n'
                '\tCreation Date: {}\n'
                '\tDue Date: {}\n'
                '\tLast Modification: {}\n'
                '>'.format(self.__id,
                           self.__name,
                           self.__description,
                           self.__caseStatus,
                           self.__caseType,
                           self.__groups,
                           self.__clientId,
                           self.__clientName,
                           self.__creationDate,
                           self.__dueDate,
                           self.__lastModificationDate))

        # -------------- getters

    @property
    def serialize(self) -> dict:
        # Return object data in easily serializable format
        print('Case Model - Serialize...')
        return {
            'caseId': self.__id,
            'name': self.__name,
            'description': self.__description,
            'status': self.__caseStatus,
            'type': self.__caseType,
            'groups': self.__groups,
            'clientId': self.__clientId,
            'clientName': self.__clientName,
            'creationDate': self.__creationDate,
            'dueDate': self.__dueDate,
            'lastModification': self.__lastModificationDate,
        }

    # ---------------------------- properties
    @property
    def caseId(self) -> str:
        # Return caseId
        return self.__id

    @property
    def caseStatus(self) -> str:
        # Return caseStatus
        return self.__caseStatus

    @property
    def caseType(self) -> str:
        # Return case type
        return self.__caseType

    @property
    def clientId(self) -> str:
        # Return case clientId
        return self.__clientId

    @property
    def clientName(self) -> str:
        # Return case clientName
        return self.__clientName

    @property
    def creationDate(self) -> datetime:
        # Return case creation date
        return self.__creationDate

    @property
    def description(self) -> str:
        # Return case description
        return self.__description

    @property
    def dueDate(self) -> datetime:
        # Return case dueDate
        return self.__dueDate

    @property
    def groups(self) -> list:
        # Return case group
        return self.__groups

    @property
    def id(self) -> str:
        # Return case id
        return self.__id

    @property
    def lastModificationDate(self) -> datetime:
        # Return case last modification date
        return self.__lastModificationDate

    @property
    def name(self) -> str:
        # Return case name
        return self.__name

    # ---------------------------- setters
    @caseStatus.setter
    def caseStatus(self, new_status) -> None:
        # Set new_status
        self.caseStatus = new_status

    @caseType.setter
    def caseType(self, new_type) -> None:
        # Set new_type
        self.__caseType = new_type

    @clientId.setter
    def clientId(self, new_clientId) -> None:
        # Set new clientId
        self.__clientId = new_clientId

    @clientName.setter
    def clientName(self, new_clientName) -> None:
        # Set new clientName
        self.__clientName = new_clientName

    @creationDate.setter
    def creationDate(self, new_date) -> None:
        # Set new case creation date
        print('new_date: ', new_date)
        self.__creationDate = self.set_current_date()

    @description.setter
    def description(self, new_description) -> None:
        # Set new case description
        self.__description = new_description

    @dueDate.setter
    def dueDate(self, new_dueDate) -> None:
        # Set new dueDate
        self.__dueDate = new_dueDate

    @groups.setter
    def groups(self, new_group_name) -> None:
        # Set new_user
        self.__groups.append(new_group_name)

    @id.setter
    def id(self, new_id) -> None:
        # Set new case id
        self.__id = new_id

    @lastModificationDate.setter
    def lastModificationDate(self, new_date) -> None:
        # Set new case lastModificationDate
        print('new_date: ', new_date)
        self.__lastModificationDate = self.set_current_date()

    @name.setter
    def name(self, new_name) -> None:
        # Set new case name
        self.__name = new_name

    # ---------------------------- static methods
    @staticmethod
    def set_current_date() -> datetime:
        # Current datetime
        return datetime.utcnow()

    @staticmethod
    def string_to_datetime(string_date) -> datetime:
        # Convert string to datetime
        print('string_date: ', string_date)
        return datetime.strptime(string_date, '%Y-%m-%dT%H:%M:%S')

application/modules/case/__init__.py
from .methods import CaseMethod
from .models import Case
from .views import case_bp

application/modules/case/views.py
"""
File path: application/modules/case/views.py
Description: Auth models for App - Define login data model
Copyright (c) 2019. This Application has been developed by OR73.
"""
# DELETE: Delete selected user
# GET: Show current user data
# POST: Create new user
# PUT: Update user data
from flask import Blueprint, flash, redirect, request, render_template, session, url_for
from flask_login import current_user, login_required
import xlrd
from _datetime import datetime

from .methods import CaseMethod

from application.modules import init_logger

case_bp = Blueprint('case_bp', __name__)


# --------------------------------------- cases
@case_bp.route('/case/<caseName>')
@login_required
def case_environment(caseName: str):
    # Create case environment
    print('------------------- case_bp.route(/case/{})'.format(caseName))
    logger = init_logger(__name__, testing_mode=False)
    logger.info('Current User: {}\n'
                '\t\tCASE - <case_environment>: The case <{}> has been selected'
                .format(current_user.username, caseName))
    return None


@case_bp.route('/case/')
@login_required
def cases():
    # Cases login
    print('----------------- case_bp.route(/cases/)')
    logger = init_logger(__name__, testing_mode=False)
    # Select user type: admin, manager or user
    print('|--- current_user: ', current_user)
    print('|--- request: ', request)
    print('|--- session: ', session)
    profile = session['profile']
    state = session['session_id']  # The same state value
    all_groups = CaseMethod.get_all_groups_name()
    print('len(all_groups): ', len(all_groups))
    if len(all_groups) > 0:
        logger.info('Current User: {}\n'
                    '\t\tCASE - <cases>: all_groups have been loaded successfully - len(all_groups): {}'
                    .format(current_user.username, len(all_groups)))
    else:
        logger.warning('Current User: {}\n'
                       '\t\tCASE - <cases>: all_groups could not be loaded - 0'
                       .format(current_user.username))
    print('case - session: ', session)
    print('case - profile: ', profile)
    # Get all cases
    all_cases = CaseMethod.get_all_cases()
    if len(all_cases) > 0:
        logger.info('Current User: {}\n'
                    '\t\tCASE - <cases>: all_cases have been loaded successfully - len(all_cases): {}'
                    .format(current_user.username, len(all_cases)))
    else:
        logger.warning('Current User: {}\n'
                       '\t\tCASE - <cases>: all_cases could not be loaded - len(all_cases): 0'
                       .format(current_user.username))
    print('all_cases: ', all_cases)
    # Show all cases & CRUD options
    return render_template('case/case_zmenu.html',
                           cases=all_cases,
                           groups=all_groups,
                           profile=profile,
                           state=state)


@case_bp.route('/cases/allGroups/')
@login_required
def allGroups():
    """
    Call CaseMethod methods to retrieve some information:
    - get_all_cases_name_id: retrieve a list of dict {'name': <case_name>, 'caseId': <caseId>}
    - get_all_groups_name: retrieve a list of dict {'name': <group_name>}
    From each list of dicts, a new list is created containing only strings>
    - casesIdList: list of all cases ID
    - casesNameList: list of all cases name
    - groupsLIst> list of all groups name
    :return: dict containing all different groups name
    """
    print('----------------- case_bp.route(/cases/allGroups/)')
    allGroupsName = CaseMethod.get_all_groups_name()
    allCasesIdAndName = CaseMethod.get_all_cases_name_id()
    
    print('allGroupsName: ', allGroupsName)
    casesIdList = []
    casesNameList = []
    groupsList = []
    
    # Create a couple of lists containing casesId and casesName
    for case in allCasesIdAndName:
        casesIdList.append(case['caseId'])
        casesNameList.append(case['name'])
    
    # Create a list containing only unique groups name
    for group in allGroupsName:
        groupsList.append(group['name'])
    print('groupsList: ', groupsList)
    return {
        'casesIdList': casesIdList,
        'casesNameList': casesNameList,
        'groupsList': groupsList
    }


@case_bp.route('/cases/allCasesNameId/')
@login_required
def allGroupsAndCases():
    print('------------------ allGroupsAndCases </cases/allCasesNameId/>')
    return CaseMethod.get_all_cases_name_id()


@case_bp.route('/case/file/', methods=['POST'])
@login_required
def caseFile():
    print('--------------------- caseFile </case/file/>')
    casesList = request.get_json()
    toReturn = CaseMethod.setClassToExcelFile(casesList)
    return toReturn


@case_bp.route('/case/upload/file/', methods=['POST'])
@login_required
def caseUploadFile():
    print('-------------------- caseUploadFile </case/upload/file>')
    print('request: ', request)
    print('request.files: ', request.files)
    caseFileData = request.files['caseFile'].read()
    # print('caseFileData: ', caseFileData)
    # Open .xls/.xlsx file and validate data
    workbook = xlrd.open_workbook(filename='format.xlsx', file_contents=caseFileData)
    sheet = workbook.sheet_by_index(0)   # 1st sheet
    print('sheet(2,1): ', sheet.cell_value(2, 1))
    print('sheet(14, 2): ', sheet.cell_value(14, 2))
    print('type(sheet(14, 2)): ', type(sheet.cell_value(14, 2)))
    print('datetime(sheet(14, 2)): ', (sheet.cell_value(14, 2)).strip().replace(' ', 'T') + ':00')
    caseData = dict(id=sheet.cell_value(3, 2),
                    name=sheet.cell_value(4, 2),
                    description=sheet.cell_value(5, 2),
                    status=sheet.cell_value(7, 1),
                    type=sheet.cell_value(7, 2),
                    groups=sheet.cell_value(8, 2),
                    clientId=sheet.cell_value(10, 2),
                    clientName=sheet.cell_value(11, 2),
                    creationDate=sheet.cell_value(13, 2),
                    dueDate=(sheet.cell_value(14, 2)).strip().replace(' ', 'T') + ':00',
                    lastModification=sheet.cell_value(15, 2),
                    )
    return CaseMethod.create_case(caseData)


@case_bp.route('/cases/<username>')
@login_required
def cases_user(username: str):
    print('------------------ case_bp.route(/case/{})'.format(username))
    logger = init_logger(__name__, testing_mode=False)
    # if current_user_profile == 'user':
    print('Current User: {}\n'
          '\t\tCASE - <cases/{}>: current user data has been loaded successfully'
          .format(current_user.username, username))
    logger.info('Current User: {}\n'
                '\t\tCASE - <cases/{}>: current user data has been loaded successfully'
                .format(current_user.username, username))
    current_user_cases_and_groups = CaseMethod.get_user_cases_and_groups_by_username(username)
    
    if current_user_cases_and_groups:
        print('Current User: {}\n'
              '\t\tCASE - <cases/{}>: current_user_cases_and_groups loaded successfully'
              .format(current_user.username, username))
        logger.info('Current User: {}\n'
                    '\t\tCASE - <cases/{}>: current_user_cases_and_groups loaded successfully'
                    .format(current_user.username, username))
    else:
        print('Current User: {}\n'
              '\t\tCASE - <cases/{}>: current_user_cases_and_groups could not be loaded'
              .format(current_user.username, username))
        logger.warning('Current User: {}\n'
                       '\t\tCASE - <cases/{}>: current_user_cases_and_groups could not be loaded'
                       .format(current_user.username, username))
    
    print('current_user_cases_and_groups: ', current_user_cases_and_groups)
    
    return render_template('case/case_user_cases.html',
                           cases=current_user_cases_and_groups,
                           language_class='flag-icon-co' if session['language'] == 'es' else 'flag-icon-us',
                           profile=current_user.profile,
                           state=request.args.get('state'),
                           title='User Cases')


@case_bp.route('/cases/user/login')
@login_required
def cases_user_login():
    print('------------------ case_bp.route(/cases/user/login)')
    current_user_username = current_user.username
    logger = init_logger(__name__, testing_mode=False)
    logger.info('Current User: {}\n'
                '\t\tCASE - <cases/user/login>: current user username: {}'
                .format(current_user.username, current_user_username))
    print('current_user_username: ', current_user_username)
    
    return redirect(url_for('case_bp.cases_user',
                            state=request.args.get('state'),
                            username=current_user_username))


@case_bp.route('/case/detail/<caseName>')
@login_required
def case_detail(caseName: str):
    print('------------------- case_bp.route(/case/detail/{})'.format(caseName))
    # Show all case data, and allows to add information (objects + meta-data) to case
    return None


@case_bp.route('/case/create/', methods=['POST'])
@login_required
def create():
    # Case create
    print('----------------- case_bp.route(/case/create/) - {}'.format(request.method))
    logger = init_logger(__name__, testing_mode=False)
    # profile = session['profile']
    currentUserUsername = current_user.username
    # if request.method == 'POST':
    caseId = request.form.get('id')
    caseGroup = request.form.get('group')
    caseName = request.form.get('name')
    caseDescription = request.form.get('description')
    caseType = request.form.get('type')
    caseStatus = request.form.get('status')
    caseDueDate = request.form.get('dueDate')
    caseClientName = request.form.get('clientName')
    caseClientId = request.form.get('clientId')
    caseClientDescription = request.form.get('clientDescription')

application/templates/case/case_create.html
<!-- templates/login/case_zmenu.html -->
<!-- show the login page case_create.html -->
{% extends 'base_login.html' %}
{% block content %}
    <nav aria-label='breadcrumb'>
        <ol class='breadcrumb'>
            <li class='breadcrumb-item'><a href='{{ url_for("case_bp.cases") }}'>{{ _('Home') }}</a> </li>
            <li class='breadcrumb-item'><a href='{{ url_for("case_bp.cases") }}'>{{ _('Cases') }}</a></li>
            <li class='breadcrumb-item active'>{{ _('Create') }}</li>
        </ol>
    </nav>
    <h1>{{ _('Create New Case') }}<small> <strong>-</strong> {{ profile }}</small></h1>

    <div class='row'>
        <div class='col'>
            <div class='text-center mb-4'>
                <img class='mb-4' src='{{ url_for("static", filename="dist/img/OWL_logo/OWL_logo_md.png") }}' alt='OWL Logo' width='190' height='75'/>
                <h1 class='h3 mb-3 font-weight-normal'>{{ _('Create New Case') }}</h1>
            </div> <!-- /.text-center -->
        </div> <!-- /.col -->
    </div> <!-- /.row -->

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class='alert alert-danger alert_message'>{{ messages[0] }}</div> <!-- /.message_alert -->
        {% endif %}
    {% endwith %}
    <div class='row h-100 justify-content-center align-items-center'>
        <form class='form-signin col-12 create_form' method='POST' action='{{ url_for("case_bp.create") }}'>
            <div class='form-label-group'>
                <input type='text' id='inputName' class='form-control' name='name' placeholder='{{ _('Name') }}' required autofocus/>
                <label for='inputName'>{{ _('Name') }}</label>
            </div> <!-- /.form-label-group -->

            <div class='form-label-group'>
                <input type='text' id='inputDescription' class='form-control' name='description' placeholder='{{ _('Description') }}' required autofocus/>
                <label for='inputDescription'>{{ _('Description') }}</label>
            </div> <!-- /.form-label-group -->

            <div class='row text-center justify-content-center'>
                <div class='col mx-auto justify-content-center'>
                    <!-- All Groups -->
                    <div class='row'>
                        <div class='col col-md-6'>
                            <fieldset class='float-right'>
                                <legend><strong>{{ _('All Groups') }}</strong></legend>
                                <ol class='box' id='all_groups'>
                                    {% for group in groups %}
                                        <li class='list_items' id='{{ group.name }}'>
                                            <input type='hidden' value='{{ group.name }}'/>
                                            {{ group.name }}
                                        </li>
                                    {% endfor %}
                                </ol>
                            </fieldset>
                        </div> <!-- /. col -->

                        <div class='col col-md-6'>
                            <fieldset class='float-left'>
                                <legend><strong>{{ _('Current Case Groups') }}</strong></legend>
                                <ol class='box' id='current_case_groups'>

                                </ol>
                            </fieldset>
                        </div> <!-- /.col -->
                    </div> <!-- /.row -->
                </div> <!-- /.col -->
            </div> <!-- /.row -->


                <!--<h3 class='label'>{ _('Groups') }}</h3>
                <small>{ _('Select one or more Groups to be added to current Case') }}</small>
                % if groups %}
                    % for group in groups %}
                        <div class='control checkbox_list'>
                            <label class='checkbox'>
                                <input type='checkbox' name='group_list' value='{ group.name }}'/>
                                { group.name }}
                            </label>
                        </div> !-- /.control --
                    % endfor %}
                % else %}
                    <h4>{ _('No groups available in Database') }}</h4>
                % endif %}
            </div> !-- /.form-label-group -->

            <div class='row text-center'>
                <div class='col'>
                    <button class='btn btn-primary' type='submit'>{{ _('Create') }}</button>
                    <a class='btn btn-danger' type='reset' href='{{ url_for("case_bp.cases") }}'>{{ _('Cancel') }}</a>
                </div> <!-- /.col -->
            </div> <!-- /.row -->
        </form>
    </div> <!-- /.row -->
{% endblock %}

application/templates/case/case_delete.html
<!-- templates/login/user_zmenu.html -->
<!-- show the login page case_delete.html -->
{% extends 'base_login.html' %}
{% block content %}
    <nav aria-label='breadcrumb'>
        <ol class='breadcrumb'>
            <li class='breadcrumb-item'><a href='{{ url_for("case_bp.cases") }}'>{{ _('Home') }}</a> </li>
            <li class='breadcrumb-item'><a href='{{ url_for("case_bp.cases") }}'>{{ _('Cases') }}</a></li>
            <li class='breadcrumb-item active'>{{ _('Delete') }}</li>
        </ol>
    </nav>
    <h1>{{ _('Delete Case') }}<small> <strong>-</strong> {{ profile }}</small></h1>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class='alert alert-danger alert_message'>{{ messages[0] }}</div> <!-- /.message_alert -->
        {% endif %}
    {% endwith %}
    {% if profile == 'admin' %}
        <section class='d-flex justify-content-center'>
            <div class='row h-100 w-100'>
                <div class='col col-md-5 w-100 mx-auto'>
                    <table class='table main_menu_table w-75'>
                        <thead>
                            <tr>
                                <th scope='col'>{{ _('Case') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class='justify-content-center'>
                                <td class='text-center create'>
                                    <a type='button' class='btn btn-outline-success'>
                                        <i class='fas fa-folder-plus i_create'></i>
                                        <span class='span_menu'> {{ _('Create Case') }}</span>
                                    </a>
                                </td>
                            </tr>
                            <tr class='justify-content-center'>
                                <td class='text-center read'>
                                    <a type='button' class='btn btn-outline-info'>
                                        <i class='fas fa-folder read i_read'></i>
                                        <span class='span_menu'> {{ _('Read Case') }}</span>
                                    </a>
                                </td>
                            </tr>
                            <tr class='justify-content-center'>
                                <td class='text-center update'>
                                    <a type='button' class='btn btn-outline-secondary'>
                                        <i class='fas fa-folder-open update i_update'></i>
                                        <span class='span_menu'> {{ _('Update Case') }}</span>
                                    </a>
                                </td>
                            </tr>
                            <tr class='justify-content-center'>
                                <td class='text-center delete'>
                                    <a type='button' class='btn btn-outline-danger'>
                                        <i class='fas fa-folder-minus delete i_delete'></i>
                                        <span class='span_menu'> {{ _('Delete Case') }}</span>
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div> <!-- /.col -->
                <div class='col col-md-5 w-100 mx-auto'>
                    <table class='table main_menu_table w-75'>
                        <thead>
                            <tr>
                                <th scope='col'>Case</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr class='justify-content-center'>
                                <td class='text-center create'>
                                    <a type='button' class='btn btn-outline-success'>
                                        <i class='fas fa-folder-plus i_create'></i>
                                        <span class='span_menu'> Create Case</span>
                                    </a>
                                </td>
                            </tr>
                            <tr class='justify-content-center'>
                                <td class='text-center read'>
                                    <a type='button' class='btn btn-outline-info'>
                                        <i class='fas fa-folder read i_read'></i>
                                        <span class='span_menu'> Read Case</span>
                                    </a>
                                </td>
                            </tr>
                            <tr class='justify-content-center'>
                                <td class='text-center update'>
                                    <a type='button' class='btn btn-outline-secondary'>
                                        <i class='fas fa-folder-open update i_update'></i>
                                        <span class='span_menu'> Update Case</span>
                                    </a>
                                </td>
                            </tr>
                            <tr class='justify-content-center'>
                                <td class='text-center delete'>
                                    <a type='button' class='btn btn-outline-danger'>
                                        <i class='fas fa-folder-minus delete i_delete'></i>
                                        <span class='span_menu'> Delete Case</span>
                                    </a>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div> <!-- /.col -->
            </div> <!-- /.row -->
        </section>

    {% elif profile == 'manager' %}
    {% elif profile == 'analyst' %}
    {% endif %}
{% endblock %}

application/templates/case/case_zmenu.html
<!-- user_login.html -->
{% extends 'base_login.html' %}
{% block content %}
    <nav aria-label='breadcrumb'>
        <ol class='breadcrumb'>
            <li class='breadcrumb-item'><a href='{{ url_for("case_bp.cases") }}'>{{ _('Home') }}</a> </li>
            <li class='breadcrumb-item active'>{{ _('Cases') }}</li>
        </ol>
    </nav>
    <h1>{{ _('Case Main Menu') }}<small> <strong>-</strong> {{ profile }}</small></h1>

    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class='alert alert-danger alert_message'>{{ messages[0] }}</div> <!-- /.message_alert -->
        {% endif %}
    {% endwith %}

    {% if profile == 'admin' or profile == 'manager' %}
        <section class='d-flex justify-content-center'>
            <div class='row h-100 w-100'>
                <div class='col col-md-6 w-100 mx-auto text-center'>
                    <a class='btn btn-outline-success main_menu_button create_button' data-placement='top'
                       href='{{ url_for("case_bp.create") }}' data-toggle='tooltip' title='Create Case'
                       type='button'>
                        <i class='fas fa-folder-plus i_create'></i>
                        <p>{{ _('Create Case') }}</p>
                    </a>
                    {% if cases %}
                        <table class='table main_menu_table w-100'>
                            <thead>
                                <tr>
                                    <th scope='col'>{{ _('Case Name') }}</th>
                                    <th scope='col'>{{ _('Description') }}</th>
                                    <th scope='col'>{{ _('Groups') }}</th><th></th><th></th><th></th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for case in cases %}
                                    <tr class='justify-content-center main_tr'>
                                        <td class='text-left align-middle'>{{ case.name }}</td>
                                        <td class='text-left align-middle'>{{ case.description }}</td>
                                        <td class='text-left align-middle'>
                                            {% for group in case.groups %}
                                                <a class='link_without_deco' href='{{ url_for("group_bp.read", group_name=group) }}'>{{ group }}</a>
                                            {% endfor %}
                                        </td>
                                        <td class='text-left align-middle'>
                                            <a class='btn btn-outline-info main_menu_button'
                                               data-toggle='tooltip' data-placement='top'
                                               title='{{ _('Read Case') }}' href='{{ url_for("case_bp.read", case_name=case.name) }}'>
                                                <i class='fas fa-folder i_read'></i>
                                            </a>
                                        </td>
                                        <td class='text-left align-middle'>
                                            <a class='btn btn-outline-secondary main_menu_button'
                                               data-toggle='tooltip' data-placement='top'
                                               title='{{ _('Update Case') }}' href='{{ url_for("case_bp.update", case_name=case.name) }}'>
                                                <i class='fas fa-folder-open i_update'></i>
                                            </a>
                                        </td>
                                        <td class='text-left align-middle'>
                                            <a class='btn btn-outline-danger main_menu_button'
                                               data-toggle='tooltip' data-placement='top'
                                               title='{{ _('Delete Case') }}' href='{{ url_for("case_bp.delete", case_name=case.name) }}'>
                                                <i class='fas fa-folder-minus i_delete'></i>
                                            </a>
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% else %}
                        <div><h2>{{ _('Database does not contain any Case') }}</h2></div>
                    {% endif %}
                </div> <!-- /.col -->
            </div> <!-- /.row -->
        </section>
    {% elif profile == 'user' %}
    {% endif %}
{% endblock %}